name: Build and Deploy
on:
  push:
    branches: [master]
  repository_dispatch:
    types: [work_update]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: Add .env File
        run: |
          echo SERVICE_DOMAIN=${{ secrets.SERVICE_DOMAIN }} >> .env
          echo API_KEY=${{ secrets.API_KEY }} >> .env

      - name: Generate static page
        run: npm run generate

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting --project=${{ secrets.FIREBASE_PROJECT_ID }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}